name: Auto Unzip Build ISO
on:
  push:
    paths:
      - "*.zip"
      - ".github/workflows/auto-unzip-build.yml"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip replace folder
        shell: powershell
        run: |
          $root = $env:GITHUB_WORKSPACE
          Get-ChildItem $root -Filter *.zip | ForEach-Object {
            $zip = $_.FullName
            $dirName = $_.BaseName
            $targetDir = Join-Path $root $dirName

            # Delete old folder
            if (Test-Path $targetDir) {
              Remove-Item $targetDir -Recurse -Force
            }
            # Create new folder
            New-Item $targetDir -ItemType Directory -Force | Out-Null
            # Extract zip
            Expand-Archive $zip -DestinationPath $targetDir -Force
            # Clean zip
            Remove-Item $zip -Force
          }

      - name: Run UUP script
        shell: cmd
        run: |
          @echo off
          for /d %%d in (Windows*_*) do (
            cd %%d
            if exist uup_download_windows.cmd call uup_download_windows.cmd
            cd ..
          )

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: Built-ISO
          path: *.iso
          retention-days: 30
