on:
  # 1. 手动点击 Run workflow 触发
  workflow_dispatch:
  # 2. 【已关闭定时】注释后不再自动定时运行（前面jia加#）
  # schedule:
  #   - cron: '0 2 * * *'
  # 3. 推送 yml/cmd 文件到 main 分支自动触发
  push:
    branches: [ main ]
    paths:
      - '**.yml'
