name: Simple Unzip Build
on:
  push:
    paths:
      - "*.zip"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        shell: powershell
        run: |
          $p=$env:GITHUB_WORKSPACE;Get-ChildItem $p -Filter *.zip|%{$n=$_.BaseName;$d="$p\$n";if(Test-Path $d){Remove-Item $d -Recurse -Force};New-Item $d -ItemType Dir -Force;Expand-Archive $_.FullName $d -Force;Remove-Item $_.FullName -Force}

      - name: Build
        shell: cmd
        run: |
          @echo off
          for /d %%d in (Windows*_*) do (
            cd %%d
            if exist uup_download_windows.cmd call uup_download_windows.cmd
            cd ..
          )

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ISO
          path: *.iso
