name: Windows11_23H2_amd64
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # 支持手动运行
env:
  FIX_RELEASE_TAG: ${{ github.ref_name }}
  FILE_NAME: Windows11_23H2_amd64
permissions:
  contents: write # 用于发布Release
jobs:
  build_pack:
    runs-on: windows-latest
    steps:
      # 拉取仓库源码
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 列出ISO校验文件存在
      - name: List ISO Files
        run: |
          cd %FILE_NAME%
          dir *.iso
          cd ..

      # 自动安装7-Zip（抛弃自带7z.exe，解决架构报错）
      - name: Install Official 7-Zip
        uses: ilammy/setup-7zip@v1

      # 分卷打包 单卷1900MB ZIP
      - name: Split Compress ZIP(1.9G/part)
        run: |
          7z a -tzip -v1900M %FIX_RELEASE_TAG%.zip ./%FILE_NAME%/*.iso -mx=6

      # 上传打包分卷为工作流制品
      - name: Upload Split Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ISO-Split-Zip-Pack
          path: |
            *.zip
            *.z01
            *.z02
            *.z*

      # 自动发布到GitHub Release
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.FIX_RELEASE_TAG }}
          name: Release ${{ env.FIX_RELEASE_TAG }}
          files: |
            *.zip
            *.z01
            *.z02
            *.z*
