name: Windows11_23H2_amd64

on: workflow_dispatch

permissions:
  contents: write

env:
  Build_VERSION: '22631.7079'
  FILE_NAME: Windows11_23H2_amd64
  FIX_TAG: Windows11_23H2_amd64

jobs:
  Windows11_23H2_amd64:
    runs-on: windows-latest

    steps:
    # 检出仓库
    - name: Checkout repository
      uses: actions/checkout@v5

    # 安装7zip
    - name: Install 7-Zip
      run: choco install 7zip -y
      env:
        PATH: "C:\\Program Files\\7-Zip;$Env:PATH"

    # UUP生成ISO
    - name: UUP dump WinISO
      shell: cmd
      run: |
        cd %FILE_NAME%
        dir
        uup_download_windows.cmd

    - name: dir dir
      shell: cmd
      run: |
        cd %FILE_NAME%
        dir

    # 1900MB分卷打包
    - name: Package binaries
      shell: cmd
      run: |
        7z a -v1900M %FIX_TAG%.7z ./%FILE_NAME%/*.iso -mx=9

    # 固定Tag发布到Release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.FIX_TAG }}
        release_name: Windows11_23H2_amd64
        overwrite: true
        files: |
          ${{ env.FIX_TAG }}.7z.*
        body: |
          编译版本：${{ env.Build_VERSION }}
          分卷规格：7z 1900MB/卷，全部下载后双击.7z.001自动解压完整ISO
