name: Windows11_23H2_amd64

on: workflow_dispatch

permissions:
  contents: write

env:
  Build_VERSION: '22631.6936'
  FILE_NAME: Windows11_23H2_amd64
  FIX_RELEASE_TAG: Windows11_23H2_amd64

jobs:
  Build_UUP:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # 一键安装7zip官方Action，稳定不会报错
      - name: Install 7-Zip
        uses: mickael-menu/setup-7zip@v1

      # UUP编译ISO
      - name: UUP dump build ISO
        shell: cmd
        run: |
          cd %FILE_NAME%
          dir
          uup_download_windows.cmd

      - name: List ISO files
        shell: cmd
        run: |
          cd %FILE_NAME%
          dir *.iso

      # ZIP分卷1900MB
      - name: Split pack ZIP(1.9G per part)
        shell: cmd
        run: |
          7z a -tzip -v1900M %FIX_RELEASE_TAG%.zip ./%FILE_NAME%/*.iso -mx=6

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FIX_RELEASE_TAG }}
          path: ${{ env.FIX_RELEASE_TAG }}.zip*

      # 固定tag发布Release
      - name: Publish to fixed Release Tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.FIX_RELEASE_TAG }}
          release_name: Windows11_23H2_amd64
          overwrite: true
          files: |
            ${{ env.FIX_RELEASE_TAG }}.zip.*
          body: |
            系统版本：Win11 23H2 Build ${{ env.Build_VERSION }}
            打包格式：标准ZIP分卷，单卷1900MB
            后缀：.zip.001/.zip.002，全下载放同一目录打开001解压
